services:
  - type: web
    name: slc-farmer-vet-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.11.7
    domains:
      - slcvet.com
